// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXEgU2HSk65PFgnqFxFsgG6au9l2I7_Fo',
    appId: '1:700892153412:web:daaf5d0ac79d0b9036de11',
    messagingSenderId: '700892153412',
    projectId: 'rider-booking-a25f7',
    authDomain: 'rider-booking-a25f7.firebaseapp.com',
    storageBucket: 'rider-booking-a25f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHog0qUU9QzHaZ2xlVAw8nSZeq5jJ_buQ',
    appId: '1:700892153412:android:38fc48ae9050141736de11',
    messagingSenderId: '700892153412',
    projectId: 'rider-booking-a25f7',
    storageBucket: 'rider-booking-a25f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0fF00FKLx1HfaYuRvQBX8dCvicqm5BPs',
    appId: '1:700892153412:ios:ad296096272b9cec36de11',
    messagingSenderId: '700892153412',
    projectId: 'rider-booking-a25f7',
    storageBucket: 'rider-booking-a25f7.firebasestorage.app',
    iosBundleId: 'com.dongasia.it3237.rideBooking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXEgU2HSk65PFgnqFxFsgG6au9l2I7_Fo',
    appId: '1:700892153412:web:369197b1f2880f0a36de11',
    messagingSenderId: '700892153412',
    projectId: 'rider-booking-a25f7',
    authDomain: 'rider-booking-a25f7.firebaseapp.com',
    storageBucket: 'rider-booking-a25f7.firebasestorage.app',
  );
}
